
calibration_optim_trace <-read.csv("./HPCmodel_calibration/HPCmodel-calibration_optim-config.csv",
                                   sep = "")

# Then, we read all the trajectories generated saving them in a list called
# ListTraces. List that will be rewritten as a data frame in order to use ggplot.
# ConfigID represents the initial condition associated to each trajectory,
# which was generated by using the function implemented in the file Functions.R .


calibration_optim_trace = calibration_optim_trace[order(calibration_optim_trace$distance),]
id.traces<-which.min(calibration_optim_trace$distance)

paste(calibration_optim_trace[id.traces,-c(1:2)],collapse = ",")
#unlist(calibration_optim_trace[id.traces,-c(1:2)] )->optimC

source('./RFunction/PlotGeneration.R')
ModelAnalysisPlot(tracefile = paste0("./HPCmodel_calibration/HPCmodel-calibration-",calibration_optim_trace[id.traces,2],".trace"))


