## Set the cluster traces to plot
cl = 2

calibration_optim_trace <-read.csv(paste0("./HPCmodel_calibration_CL",cl,"/HPCmodel-calibration_optim-config.csv"),
                                   sep = "")

# Then, we read all the trajectories generated saving them in a list called
# ListTraces. List that will be rewritten as a data frame in order to use ggplot.
# ConfigID represents the initial condition associated to each trajectory,
# which was generated by using the function implemented in the file Functions.R .


calibration_optim_trace = calibration_optim_trace[order(calibration_optim_trace$distance),]

# To remove all the traces from the calibration without the best one.

# file.remove(paste0("./HPCmodel_calibration_CL",cl,"/HPCmodel-calibration-",
#                    calibration_optim_trace[2:length(calibration_optim_trace$distance),2],".trace"))


source('./RFunction/PlotGeneration.R')

ModelAnalysisPlot(
  tracefile = paste0("./HPCmodel_calibration_CL",cl,"/HPCmodel-calibration-",calibration_optim_trace[1,2],".trace"),
  referencefile = paste0("Input/ReferenceCl",cl,".csv"),
  Namefile = paste0("CL",cl)
  )


