#interval = "c3"

source('~/Model_ADMIREproj/RFunction/PlotGeneration.R')

p = list()
Values = list()
k = 1
for(interval in c("c1","c2","c3")){
setwd(dir = paste0("~/Model_ADMIREproj/Calibration/Interval_",interval,"/") )

calibration_optim_trace <-read.csv(paste0("./queueHPCmodel_calibration/queueHPCmodel-calibration_optim-config.csv"),
                                   sep = "")

# Then, we read all the trajectories generated saving them in a list called
# ListTraces. List that will be rewritten as a data frame in order to use ggplot.
# ConfigID represents the initial condition associated to each trajectory,
# which was generated by using the function implemented in the file Functions.R .


calibration_optim_trace = calibration_optim_trace[order(calibration_optim_trace$distance),]

# To remove all the traces from the calibration without the best one.

# file.remove(paste0("./HPCmodel_calibration_CL",cl,"/HPCmodel-calibration-",
#                    calibration_optim_trace[2:length(calibration_optim_trace$distance),2],".trace"))



pl = ModelAnalysisPlot(
  tracefile = paste0("./queueHPCmodel_calibration/queueHPCmodel-calibration-",
                     calibration_optim_trace[1,2],
                     ".trace"),
  timestrace = paste0("queueHPCmodel_calibration/timedPlace-",calibration_optim_trace[1,2],".trace"),
  referencefile = "Input/Reference/CompleteTraceplot8Deltas.RDs"
  )

reference <- as.data.frame(t(read.csv(paste0("Input/Reference/",interval,"_plot8Deltas.csv"),
                                      header = FALSE, sep = "")))
colnames(reference) = c("Time", "Cluster", "io_p","iops","mpi_hit","mpi_p")
reference$Time = reference$Time +1

a = merge(pl$layers[[2]]$data,reference %>% tidyr::gather(-Time,-Cluster,value="RefMeasure",key = "Jobs"))
Values[[k]] = a %>% mutate(Diff = abs(RefMeasure - Mean) )#/RefMeasure)

paramsName = readRDS("Input/paramsNAMES.RDs")
params <- calibration_optim_trace[1,-c(1,2)]

p[[k]] = paste0("params[\"",grep(x=paramsName,pattern = paste0("_",interval),value = T),"\"] = ",params)
k = k+1
}

format(do.call(rbind,Values), scientific=FALSE)

setwd("~/Model_ADMIREproj")
write.table(unlist(p),file = "params",quote = F,row.names = F,col.names = F)
